package Ghrandal.codecity;

import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.Files; import java.util.*;

final class ArchitectureReportExporter {
    private ArchitectureReportExporter(){}
    static void write(Model m, File file) throws IOException {
        MetricsReport r=new MetricsReport(m); StringBuilder h=new StringBuilder();
        h.append("<!doctype html><html><head><meta charset='utf-8'><title>").append(e(m.name)).append(" Architecture Report</title><style>");
        h.append("body{font-family:system-ui;background:#0e1116;color:#e8ebef;margin:40px}table{border-collapse:collapse;width:100%}th,td{padding:8px;border-bottom:1px solid #2a313c;text-align:left}th{color:#9aa3b0} .high{color:#ff9b71}.critical{color:#ff5f56}.medium{color:#ffd166}.low{color:#7ee787}.card{display:inline-block;background:#20252e;padding:16px;margin:6px;border-radius:8px;min-width:140px}</style></head><body>");
        h.append("<h1>").append(e(m.name)).append("</h1><p>Generated by GhrandalCodeCity.</p>");
        card(h,"LOC",r.loc);card(h,"Packages",r.packages);card(h,"Classes",r.types);card(h,"Methods",r.methods);card(h,"Attributes",r.attributes);card(h,"Relations",r.relations);
        h.append("<h2>Quality hotspots</h2><table><tr><th>Class</th><th>LOC</th><th>WMC*</th><th>RFC*</th><th>CBO*</th><th>DIT</th><th>NOC</th><th>Fan-Out</th><th>Quality</th></tr>");
        for(MetricSnapshot x:r.hotspots()){String q=MetricsEngine.quality(x).toLowerCase(Locale.ROOT);h.append("<tr><td>").append(e(x.type.fullName())).append("</td><td>").append(x.loc).append("</td><td>").append(x.wmcEstimated).append("</td><td>").append(x.rfcEstimated).append("</td><td>").append(x.cboEstimated).append("</td><td>").append(x.dit).append("</td><td>").append(x.noc).append("</td><td>").append(x.fanOut).append("</td><td class='").append(q).append("'>").append(q).append("</td></tr>");}
        h.append("</table><p><small>* WMC/RFC/CBO are estimates based on the available XML model.</small></p></body></html>"); Files.writeString(file.toPath(),h.toString(),StandardCharsets.UTF_8);
    }
    private static void card(StringBuilder h,String n,int v){h.append("<div class='card'><b>").append(n).append("</b><br><span style='font-size:24px'>").append(v).append("</span></div>");}
    private static String e(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
}
